services:
  - type: web
    name: examen-guinee-insights-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: examen-guinee-insights-backend
          property: port
    disk:
      name: data-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1
